# Let's try running on PnP and switch to node_modules if something breaks
#nodeLinker: node-modules
nodeLinker: pnp
npmRegistryServer: "https://registry.npmjs.org"
enableGlobalCache: true
packageExtensions:
  typedoc@*:
    peerDependencies:
      typedoc-plugin-missing-exports: "*"
      typedoc-plugin-resolve-crossmodule-references: "*"
      typedoc-plugin-mdn-links: "*"
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
