# Let's try running on PnP and switch to node_modules if something breaks
#nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
enableGlobalCache: true
packageExtensions:
  typedoc@*:
    peerDependencies:
      typedoc-plugin-missing-exports: "*"
      typedoc-plugin-resolve-crossmodule-references: "*"
      typedoc-plugin-mdn-links: "*"
  "@opendesign/octopus-fig@*":
    dependencies:
      # let's match version with @opendesign/figma-parser
      eventemitter3: "^4.0.7"
