name: Setup Yarn

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: "yarn"
    - name: Setup corepack
      run: corepack enable yarn
      shell: bash
    - name: Setup .yarnrc.yml
      run: |
        yarn config set enableGlobalCache false
      shell: bash
    - run: yarn install --immutable
      shell: bash
