name: Setup Yarn

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 19.x
        cache: "yarn"
    - name: Setup corepack
      run: corepack enable yarn
      shell: bash
    - name: Setup .yarnrc.yml
      run: |
        yarn config set enableGlobalCache false
      shell: bash
    - uses: actions/cache@v3
      with:
        path: .yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn install --immutable
      shell: bash
