---
name: "Deploy to Dokku"

on:
  push:
    branches:
      - main

jobs:
  deploy_review_app:
    runs-on: ubuntu-latest
    environment:
      name: "staging"
      url: https://odf.dokku.opendesign.site
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: dokku
        uses: ./.github/actions/setup_dokku
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          app_name: odf
      - name: Push to dokku
        shell: bash
        run: git push --no-verify --force dokku HEAD:refs/heads/main
