---
name: "deploy"

on:
  # only run this workflow on pull request events
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review_app:
    runs-on: ubuntu-latest
    # only run when a pull request is open
    if: github.event.pull_request.state == 'open'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          # create a review app
          command: review-apps:create
          git_remote_url: "ssh://dokku@dokku.opendesign.site:22/odf"
          git_push_flags: --no-verify # <- works around missing git-lfs
          branch: main
          # specify a name for the review app
          review_app_name: review-odf-${{ github.event.pull_request.number }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  destroy_review_app:
    runs-on: ubuntu-latest
    # only run when a pull request is closed
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Destroy the review app
        uses: dokku/github-action@master
        with:
          # destroy a review app
          command: review-apps:destroy
          git_remote_url: "ssh://dokku@dokku.opendesign.site:22/odf"
          git_push_flags: --no-verify # <- works around missing git-lfs
          branch: main
          # specify a name for the review app
          review_app_name: review-odf-${{ github.event.pull_request.number }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
